name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.5
  loading_animation_widget: ^1.3.0
  like_button: ^2.1.0
  permission_handler: ^11.4.0
  vibration: ^1.7.6
  fluttertoast: ^8.2.12
 

 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.1.0  

     
 


  
 

 


flutter:
  uses-material-design: true
  assets: 
  - lib/image/
